version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: ${WORDPRESS_WEBSITE_TITLE}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: ${WORDPRESS_WEBSITE_TITLE}_pma
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: ${WORDPRESS_WEBSITE_TITLE}_wp
    ports:
      - '8000:80'
    restart: always
    volumes: ['./${SITE_DIR}:/var/www/html', './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_PREFIX}
    networks:
      - wpsite
  # WP-CLI
  cli:
    build: 
      context: ./cli/
    container_name: wpcli
    image: cli
    volumes: ['./${SITE_DIR}:/var/www/html']
    
    networks:
     - wpsite
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_PREFIX}
    working_dir: /var/www/html
  
  node:
    build: ./node/
    image: node:16.16.0
    working_dir: /var/www/html/wp-content/themes/cedctheme
    command: yarn install
    container_name: cedc_node
    volumes:
      - ./${SITE_DIR}/wp-content/themes/cedctheme:/var/www/html/wp-content/themes/cedctheme
      - /var/www/html/wp-content/themes/cedctheme/node_modules
    ports:
      - "3000:3000"

networks:
  wpsite:
volumes:
  db_data: