version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cedc
      MYSQL_DATABASE: cedc
      MYSQL_USER: cedc
      MYSQL_PASSWORD: cedc
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./html:/var/www/html', './uploads.ini:/usr/local/etc/php/conf.d/uploads.ini']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: cedc
      WORDPRESS_DB_NAME: cedc
      WORDPRESS_DB_PASSWORD: cedc
      WORDPRESS_TABLE_PREFIX: cedc_
    networks:
      - wpsite
  # WP-CLI
  cli:
    build: 
      context: ./cli/
      args:
        USER_ID: 1050106
        USER_GROUP: 1049089
    container_name: wpcli
    image: cli
    volumes: ['./html:/var/www/html']
    
    networks:
     - wpsite
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: cedc
      WORDPRESS_DB_NAME: cedc
      WORDPRESS_DB_PASSWORD: cedc
      WORDPRESS_TABLE_PREFIX: cedc_
    working_dir: /var/www/html
  
  node:
    build: ./node/
    command: npm init -y
    container_name: cedc_node
    volumes:
      - ./html/:/var/www/html/
      - /var/www/html/wp-content/themes/cedctheme/node_modules
    ports:
      - "3000:3000"

networks:
  wpsite:
volumes:
  db_data: